#Data Cleaning Project

##1.Import Libraries

In [1]:
import pandas as pd  
import numpy as np

##2.Load Dataset

In [2]:
df = pd.read_excel("../data/First Dataset.xlsx")

In [3]:
##3.Dataset Overview

In [4]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [5]:
df.shape

(61, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [7]:
df.columns

Index(['customer_id', 'first_name', 'gender', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score'],
      dtype='object')

In [8]:
df.describe(include="all")

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
count,61.000000,61,61,60.000000,61,61,61,61,61.000000,61.000000,60.000000,61.000000,61,61,61,61.000000,61.00000
unique,NaN,12,2,NaN,8,8,58,4,NaN,NaN,NaN,NaN,3,3,2,NaN,NaN
top,NaN,Reza,F,NaN,Tabriz,East Azerbaijan,2021-11-08,Gold,NaN,NaN,NaN,NaN,Online Wallet,Android,No,NaN,NaN
freq,NaN,8,35,NaN,13,13,2,19,NaN,NaN,NaN,NaN,23,23,35,NaN,NaN
mean,1030.229508,NaN,NaN,45.200000,NaN,NaN,NaN,NaN,17.606557,211.435738,3749.667333,196.934426,NaN,NaN,NaN,4.196721,3.00000
std,17.446483,NaN,NaN,19.167239,NaN,NaN,NaN,NaN,10.214824,130.113726,4262.248522,97.892436,NaN,NaN,NaN,2.663454,1.42595
min,1001.000000,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,0.000000,27.630000,0.000000,3.000000,NaN,NaN,NaN,0.000000,1.00000
25%,1015.000000,NaN,NaN,31.750000,NaN,NaN,NaN,NaN,11.000000,108.190000,1167.035000,132.000000,NaN,NaN,NaN,2.000000,2.00000
50%,1030.000000,NaN,NaN,45.000000,NaN,NaN,NaN,NaN,17.000000,161.330000,2188.865000,201.000000,NaN,NaN,NaN,4.000000,3.00000
75%,1045.000000,NaN,NaN,58.000000,NaN,NaN,NaN,NaN,26.000000,323.320000,4692.150000,273.000000,NaN,NaN,NaN,7.000000,4.00000
max,1060.000000,NaN,NaN,145.000000,NaN,NaN,NaN,NaN,35.000000,449.810000,25000.000000,365.000000,NaN,NaN,NaN,8.000000,5.00000

## 4. Missing Values Analysis

In [9]:
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [10]:
(df.isnull().sum()/len(df))*100

customer_id           0.000000
first_name            0.000000
gender                0.000000
age                   1.639344
city                  0.000000
province              0.000000
signup_date           0.000000
membership_tier       0.000000
purchase_count        0.000000
avg_order_value       0.000000
total_spending        1.639344
last_purchase_days    0.000000
payment_method        0.000000
device                0.000000
discount_used         0.000000
returned_items        0.000000
satisfaction_score    0.000000
dtype: float64

### Findings 
No missing value were detected in the dataset.

## 5. Duplicate Records Analysis

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df[df.duplicated()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

## 6. Data Types Validation

In [13]:
df.dtypes

customer_id             int64
first_name             object
gender                 object
age                   float64
city                   object
province               object
signup_date            object
membership_tier        object
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method         object
device                 object
discount_used          object
returned_items          int64
satisfaction_score      int64
dtype: object

## 7. Date Format Validation

In [14]:
df["signup_date"].head()

0    2025-02-19
1    2022-08-19
2    2023-06-20
3    2021-11-08
4    2021-10-21
Name: signup_date, dtype: object

In [15]:
df["signup_date"] = pd.to_datetime(df["signup_date"], errors="coerce")

In [16]:
df["signup_date"].dtype

dtype('<M8[ns]')

## 8. Invalid Values Detection

In [17]:
df[(df["age"] < 0) | (df["age"] > 100)]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [18]:
df[df["purchase_count"] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [19]:
df[df["avg_order_value"] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [20]:
df[df["total_spending"] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [21]:
df[df["last_purchase_days"] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [22]:
df[(df["satisfaction_score"] < 1) | (df["satisfaction_score"] > 5)]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

## 9. Outlier Detection Using IQR

In [23]:
numeric_columns = [
    "age",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "last_purchase_days",
    "returned_items",
    "satisfaction_score",
]

In [24]:
for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col}: {len(outliers)} outliers")

age: 1 outliers
purchase_count: 0 outliers
avg_order_value: 0 outliers
total_spending: 5 outliers
last_purchase_days: 0 outliers
returned_items: 0 outliers
satisfaction_score: 0 outliers

## 10. Extra Spaces Detection

In [25]:
text_columns = [
    "first_name",
    "city",
    "province",
    "membership_tier",
    "payment_method",
    "device"
]

for col in text_columns:
    print(f"\nColumn: {col}")
    print("Leading spaces:", df[col].str.startswith(" ").sum())
    print("Trailing spaces:", df[col].str.endswith(" ").sum())
    print(col)
    print(df[col].str.startswith(" "). sum())
    print(df[col].str.endswith(" ").sum())

Column: first_name
Leading spaces: 0
Trailing spaces: 0
first_name
0
0

Column: city
Leading spaces: 0
Trailing spaces: 0
city
0
0

Column: province
Leading spaces: 0
Trailing spaces: 0
province
0
0

Column: membership_tier
Leading spaces: 0
Trailing spaces: 0
membership_tier
0
0

Column: payment_method
Leading spaces: 0
Trailing spaces: 0
payment_method
0
0

Column: device
Leading spaces: 0
Trailing spaces: 0
device
0
0

## 11. Inconsistent Names and Typographical Errors

In [27]:
for col in [
    "gender",
    "city",
    "province",
    "membership_tier",
    "payment_method",
    "device"
]:
    print(col)
    print(df[col].value_counts())

gender
gender
F    35
M    26
Name: count, dtype: int64
city
city
Tabriz     13
Mashhad    11
Ahvaz       8
Karaj       7
Tehran      6
Shiraz      6
Isfahan     5
Rasht       5
Name: count, dtype: int64
province
province
East Azerbaijan    13
Khorasan           11
Khuzestan           8
Alborz              7
Tehran              6
Fars                6
Isfahan             5
Gilan               5
Name: count, dtype: int64
membership_tier
membership_tier
Gold      19
Bronze    18
VIP       16
Silver     8
Name: count, dtype: int64
payment_method
payment_method
Online Wallet    23
Card             19
Cash             19
Name: count, dtype: int64
device
device
Android    23
Web        20
iPhone     18
Name: count, dtype: int64

## 12.column Consistency Check

This section checks whether the total spending is consistent with the purchase count and average order value.

In [28]:
df["expected_total"] = df["purchase_count"] * df["avg_order_value"]
df["difference"] = df["total_spending"] - df["expected_total"]
df["difference"].describe()
df[abs(df["difference"]) > 0.01]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,expected_total,difference
29,1030,Sina,M,60.0,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4,4079.14,20920.86

## 13. Save Cleaned Dataset

In [29]:
df.to_excel("../data/cleaned_First Dataset.xlsx", index=False)